name: Print Hello World
on:
  push:
jobs:
  print: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Print hello
        run: node backend/my-app.js
    